export const productData = [
  {
    id: 1,
    title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    price: 109.95,
    category: "men's clothing",
    customer: {
      name: 'John Doe',
      email: 'johndoe@example.com',
      address: '123 Main St, Anytown, USA',
      phone: '555-123-4567',
    },
    payment: {
      card_number: '**** **** **** 1234',
      expiration_date: '12/25',
      cvv: '***',
    },
    timestamp: '2024-03-01T12:00:00Z',
    order_status: 'pending',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 10.0,
    total_price: 124.95,
    notes: 'Gift wrap requested',
  },
  {
    id: 2,
    title: "Men's Casual Slim Fit Shirts",
    price: 29.99,
    category: "men's clothing",
    customer: {
      name: 'Jane Smith',
      email: 'janesmith@example.com',
      address: '456 Oak St, Smalltown, USA',
      phone: '555-987-6543',
    },
    payment: {
      card_number: '**** **** **** 5678',
      expiration_date: '10/24',
      cvv: '***',
    },
    timestamp: '2024-03-02T10:30:00Z',
    order_status: 'processing',
    shipping_method: 'express',
    shipping_cost: 10.0,
    tax: 5.0,
    total_price: 44.99,
    notes: 'No special requests',
  },
  {
    id: 3,
    title: 'Apple AirPods Pro',
    price: 249.0,
    customer: {
      name: 'Mike Johnson',
      email: 'mikejohnson@example.com',
      address: '789 Elm St, Bigcity, USA',
      phone: '555-555-5555',
    },
    payment: {
      card_number: '**** **** **** 9012',
      expiration_date: '05/26',
      cvv: '***',
    },
    timestamp: '2024-03-03T15:45:00Z',
    order_status: 'shipped',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 20.0,
    total_price: 274.0,
    notes: 'Signature required upon delivery',
  },
  {
    id: 4,
    title: "Women's Running Shoes",
    price: 89.95,
    customer: {
      name: 'Emily Brown',
      email: 'emilybrown@example.com',
      address: '101 Pine St, Mountainside, USA',
      phone: '555-321-7890',
    },
    payment: {
      card_number: '**** **** **** 3456',
      expiration_date: '08/23',
      cvv: '***',
    },
    timestamp: '2024-03-04T09:15:00Z',
    order_status: 'delivered',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 15.0,
    total_price: 109.95,
    notes: 'No returns or exchanges',
  },
  {
    id: 5,
    title: 'Samsung 65-Inch 4K Ultra HD Smart TV',
    price: 999.99,
    category: 'electronics',
    customer: {
      name: 'Michael Williams',
      email: 'michaelwilliams@example.com',
      address: '246 Maple Ave, Suburbia, USA',
      phone: '555-456-1234',
    },
    payment: {
      card_number: '**** **** **** 7890',
      expiration_date: '03/28',
      cvv: '***',
    },
    timestamp: '2024-03-05T18:00:00Z',
    order_status: 'processing',
    shipping_method: 'express',
    shipping_cost: 20.0,
    tax: 50.0,
    total_price: 1069.99,
    notes: 'Installment payment plan requested',
  },
  {
    id: 6,
    title: "Women's Leather Crossbody Bag",
    price: 49.99,
    category: "women's accessories",
    customer: {
      name: 'Jessica Taylor',
      email: 'jessicataylor@example.com',
      address: '369 Walnut St, Downtown, USA',
      phone: '555-789-4561',
    },
    payment: {
      card_number: '**** **** **** 2345',
      expiration_date: '09/25',
      cvv: '***',
    },
    timestamp: '2024-03-06T11:30:00Z',
    order_status: 'pending',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 7.5,
    total_price: 62.49,
    notes: 'Gift message included',
  },
  {
    id: 7,
    title: 'Fitbit Charge 4 Fitness and Activity Tracker',
    price: 129.95,
    category: 'electronics',
    customer: {
      name: 'David Rodriguez',
      email: 'davidrodriguez@example.com',
      address: '852 Birch St, Riverside, USA',
      phone: '555-987-6543',
    },
    payment: {
      card_number: '**** **** **** 6789',
      expiration_date: '11/27',
      cvv: '***',
    },
    timestamp: '2024-03-07T14:45:00Z',
    order_status: 'shipped',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 15.0,
    total_price: 149.95,
    notes: 'No special requests',
  },
  {
    id: 8,
    title: "Kids' Toy Kitchen Playset",
    price: 49.99,
    category: 'toys',
    customer: {
      name: 'Sarah Clark',
      email: 'sarahclark@example.com',
      address: '753 Cedar St, Parkville, USA',
      phone: '555-369-2580',
    },
    payment: {
      card_number: '**** **** **** 1234',
      expiration_date: '07/24',
      cvv: '***',
    },
    timestamp: '2024-03-08T16:00:00Z',
    order_status: 'processing',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 7.5,
    total_price: 62.49,
    notes: 'Assembly required',
  },
  {
    id: 9,
    title: "Men's Waterproof Hiking Boots",
    price: 79.99,
    category: "men's shoes",
    customer: {
      name: 'Chris Wilson',
      email: 'chriswilson@example.com',
      address: '987 Spruce St, Lakeside, USA',
      phone: '555-741-8520',
    },
    payment: {
      card_number: '**** **** **** 3456',
      expiration_date: '04/26',
      cvv: '***',
    },
    timestamp: '2024-03-09T09:30:00Z',
    order_status: 'delivered',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 10.0,
    total_price: 94.99,
    notes: 'No special requests',
  },
  {
    id: 10,
    title: "Women's Yoga Pants",
    price: 34.99,
    category: "women's clothing",
    customer: {
      name: 'Amy Lee',
      email: 'amylee@example.com',
      address: '369 Pine St, Beachtown, USA',
      phone: '555-852-3690',
    },
    payment: {
      card_number: '**** **** **** 9012',
      expiration_date: '06/25',
      cvv: '***',
    },
    timestamp: '2024-03-10T12:15:00Z',
    order_status: 'pending',
    shipping_method: 'standard',
    shipping_cost: 5.0,
    tax: 7.0,
    total_price: 46.99,
    notes: 'Size small, color: black',
  },
];
